export const dict = {
  ar: {
    app: {
      name: "البورصة الوطنية للبطاطا",
      nameEn: "National Potato Exchange",
      tagline: "منصة التداول الإلكترونية للبطاطا في السوق الجزائري",
      authority: "المحافظة السامية للرقمنة — تحت إشراف الدولة",
    },
    nav: {
      market: "السوق",
      trading: "التداول",
      auctions: "المزادات",
      receipts: "إيصالات المستودعات",
      stores: "المخازن الباردة",
      intervention: "تدخل الدولة",
      trace: "التتبع",
      dashboard: "فضائي",
      login: "الدخول",
      logout: "خروج",
      language: "English",
      proposal: "عن المشروع",
    },
    common: {
      loading: "جارٍ التحميل…",
      all: "الكل",
      status: "الحالة",
      actions: "إجراءات",
      save: "حفظ",
      cancel: "إلغاء",
      confirm: "تأكيد",
      price: "السعر",
      priceKg: "السعر (دج/كغ)",
      quantity: "الكمية",
      quantityQ: "الكمية (قنطار)",
      grade: "الدرجة",
      total: "المجموع",
      totalValue: "القيمة الإجمالية",
      date: "التاريخ",
      buy: "شراء",
      sell: "بيع",
      today: "اليوم",
      yesterday: "أمس",
      perKg: "دج/كغ",
      quintal: "قنطار",
      quintals: "قنطار",
      ton: "طن",
      dzd: "دج",
      live: "مباشر",
      refresh: "تحديث",
      noData: "لا توجد بيانات",
      search: "بحث برمز الإيصال أو الدفعة…",
      volume: "الحجم",
      bid: "عرض شراء",
      ask: "عرض بيع",
      spread: "فارق السعر",
      depth: "عمق السوق",
      recentTrades: "آخر الصفقات",
      orderBook: "سجل الأوامر",
      placeOrder: "إصدار أمر",
      orderType: "نوع الأمر",
      limit: "محدد السعر",
      auction: "مزاد",
      open: "مفتوح",
      partial: "منفذ جزئياً",
      filled: "منفذ",
      cancelled: "ملغى",
      active: "نشط",
      pledged: "مرهون",
      transferred: "محول",
      delivered: "مُسلَّم",
      settled: "مسوّى",
      inspected: "مُعايَن",
      pending: "قيد الانتظار",
      buyer: "المشتري",
      seller: "البائع",
      holder: "الحائز",
      view: "عرض",
      details: "التفاصيل",
      back: "عودة",
      official: "رسمي",
      certified: "معتمد",
      connected: "مرتبط رقمياً",
      demo: "بيانات تجريبية",
      wallet: "المحفظة",
      gradeA: "الدرجة أ — تصدير/ممتازة",
      gradeB: "الدرجة ب — استهلاك معياري",
      gradeC: "الدرجة ج — تحويل صناعي",
      variety: "الصنف",
      wilaya: "الولاية",
      code: "الرمز",
      role: "الصفة",
      loginAs: "الدخول كـ",
      minutes: "دقيقة",
      hours: "ساعة",
      days: "يوم",
      closed: "مغلق",
      winner: "الفائز",
      settlePrice: "سعر التسوية",
      quantityAvailable: "الكمية المتاحة",
    },
    roles: {
      farmer: "فلاح",
      trader: "تاجر",
      state: "مؤسسة عمومية (ONILEV)",
      warehouse: "مستودع تبريد",
      bank: "بنك",
      processor: "مُحوِّل صناعي",
      admin: "هيئة الضبط",
    },
    landing: {
      heroBadge: "مشروع قابل للتنفيذ تحت إشراف الدولة",
      heroTitle: "بورصة وطنية فورية للبطاطا",
      heroSubtitle:
        "تداول شفاف، إيصالات مستودعات إلكترونية قابلة للرهن، ودولة صانعة سوق تحمي الفلاح والمستهلك",
      ctaTrade: "ابدأ التداول",
      ctaProposal: "مكونات المنصة",
      statProduction: "الإنتاج السنوي",
      statConsumption: "الاستهلاك الوطني",
      statStock: "المخزون الاستراتيجي",
      statVolatility: "نطاق تقلب الأسعار",
      marketTitle: "مؤشر السوق اليوم",
      marketSubtitle: "السعر المرجعي والحجم المسجّل على المنصة",
      refPrice: "السعر المرجعي",
      floor: "سعر التدخل بالشراء (أرضية)",
      ceiling: "سعر التدخل بالبيع (سقف)",
      todayVolume: "حجم اليوم",
      stateStock: "مخزون الدولة الاستراتيجي",
      chartTitle: "تطور الأسعار خلال 120 يوماً",
      chartSubtitle: "مع نطاق تدخل الدولة لكبح التقلب",
      componentsTitle: "مكونات المنصة",
      componentsSubtitle: "خمسة مكونات مترابطة تديرها هيئة تشغيلية تحت إشراف الوزارات",
      cSpotTitle: "التداول الفوري",
      cSpotText: "مزادات يومية ومطابقة مستمرة للأوامر لاكتشاف سعر عادل وشفاف.",
      cReceiptTitle: "إيصالات المستودعات",
      cReceiptText: "إيصالات إلكترونية موثقة قابلة للتداول والرهن البنكي مقابل التمويل.",
      cMmTitle: "الدولة صانعة سوق",
      cMmText: "شراء عند انخفاض الأسعار وبيع من المخزون الاستراتيجي عند ارتفاعها.",
      cQualityTitle: "الجودة والمعايير",
      cQualityText: "تصنيف معتمد (درجة، حجم، رطوبة) مرتبط بالمخازن الباردة والمختبرات.",
      cIntegrationTitle: "التكامل الرقمي",
      cIntegrationText: "ربط مع BaridiMob والبنوك والمركز الوطني للسجل التجاري ووسائل الدفع المحلية.",
      roadmapTitle: "خارطة الطريق (18–24 شهراً)",
      phases: "أربع مراحل",
      phase1Title: "التحضير — 3 إلى 4 أشهر",
      phase1Text: "لجنة قيادة، دراسة جدوى، صياغة النصوص القانونية، تصميم النظام.",
      phase2Title: "البناء — 6 إلى 8 أشهر",
      phase2Text: "تطوير المنصة وربط المخازن وتدريب الفرق وإصدار أولي (MVP).",
      phase3Title: "التجريب — 4 إلى 6 أشهر",
      phase3Text: "إطلاق تجريبي في 2–3 ولايات منتجة وتقييم وتحسين.",
      phase4Title: "التعميم — 5 إلى 6 أشهر",
      phase4Text: "توسيع وطني وربط شامل وإطلاق رسمي ومتابعة.",
      legalTitle: "الإطار القانوني",
      legalText:
        "قانون التجارة الإلكترونية 18-05، صلاحيات ONILEV وSARPA، نظام سيربالاك، ونصوص تأسيسية لإيصالات المستودعات وصناعة السوق.",
      offlineTitle: "تعمل في كل مكان",
      offlineText: "تطبيق يعمل دون اتصال، واجهة عربية مبسطة، دعم SMS/USSD ووكلاء محليين مع استضافة وطنية سيادية.",
    },
    trading: {
      title: "قاعة التداول",
      subtitle: "مطابقة مستمرة للأوامر — سعر السوق يحدده العرض والطلب ضمن نطاق تدخل الدولة",
      buy: "أمر شراء",
      sell: "أمر بيع",
      buyDesc: "تسجيل طلب شراء بسعرك المحدد",
      sellDesc: "بع إنتاجك أو إيصالك مباشرة في السوق",
      pricePlaceholder: "السعر الأقصى للشراء (دج/كغ)",
      pricePlaceholderSell: "السعر الأدنى للبيع (دج/كغ)",
      qtyPlaceholder: "الكمية بالقناطر",
      submitBuy: "إرسال أمر الشراء",
      submitSell: "إرسال أمر البيع",
      myOrders: "أوامري",
      bestBid: "أفضل عرض شراء",
      bestAsk: "أفضل عرض بيع",
      marketTick: "تحديث لحظي",
      tickHint: "محاكاة ديناميكية لوصول أوامر جديدة ومطابقتها",
      orderPlaced: "تم تسجيل الأمر وإجراء المطابقة",
      orderFailed: "تعذّر تسجيل الأمر",
      orderCancelled: "تم إلغاء الأمر",
      cancel: "إلغاء",
      stateLiquidity: "سيولة الدولة عند الحدّين",
      bidQty: "كمية العرض",
      askQty: "كمية الطلب",
      priceLevel: "السعر",
      matched: "تمت المطابقة",
      noReceipt: "بيع حر (تسليم لاحق)",
      againstReceipt: "مقابل إيصال مستودع",
      selectReceipt: "اختر إيصالاً للبيع…",
      connectToTrade: "سجّل الدخول لإصدار الأوامر",
      selectGrade: "اختر الدرجة",
      fundHint: "القيمة تُخصم من المحفظة عند التسوية",
      sellReceiptHint: "البيع المرتبط بإيصال يحوّل ملكية البضاعة المخزّنة",
      depthTitle: "عمق السوق (تراكمي)",
      stateOrder: "أمر الدولة",
    },
    auctions: {
      title: "المزادات اليومية",
      subtitle: "مزاد موحّد السعر يُقفل يومياً على الساعة 11:00 — يُباع الإنتاج بسعر أعلى إغلاق",
      liveAuction: "المزاد الجاري",
      scheduledAt: "موعد القفل",
      quantityOffered: "الكمية المعروضة",
      leadingBid: "أعلى عرض",
      bidCount: "عدد العروض",
      placeBid: "تقديم عرض",
      yourBid: "عرضك (دج/كغ)",
      settled: "مزادات مسوّاة",
      settle: "تسوية المزاد الآن",
      settledAt: "سعر التسوية",
      seller: "العارض",
      noLive: "لا يوجد مزاد جارٍ حالياً",
      pastResults: "نتائج المزادات السابقة",
      bidPlaced: "تم تسجيل عرضك",
      settledOk: "تمت تسوية المزاد",
      loginToBid: "سجّل الدخول لتقديم عرض",
      qtyBid: "الكمية المطلوبة (قنطار)",
      remaining: "متبقٍّ على القفل",
    },
    receipts: {
      title: "إيصالات المستودعات الإلكترونية",
      subtitle: "إثبات ملكية قابل للتداول والرهن البنكي — يصدره مستودع تبريد معتمد",
      issue: "إصدار إيصال جديد",
      myReceipts: "إيصالاتي",
      allReceipts: "كل الإيصالات",
      code: "رقم الإيصال",
      lot: "الدفعة",
      store: "المستودع",
      issueDate: "تاريخ الإصدار",
      available: "الكمية المتاحة",
      pledge: "رهن لدى البنك",
      pledgeHint: "تمويل مقابل 70% من قيمة الإيصال",
      pledged: "مرهون",
      pledgeAmount: "مبلغ التمويل",
      release: "فك الرهن",
      sellOnExchange: "بيع في البورصة",
      transfer: "تحويل ملكية",
      trace: "تتبع الدفعة",
      farmer: "الفلاح",
      newReceiptTitle: "إيداع إنتاج وإصدار إيصال",
      selectFarmer: "الفلاح المودِع",
      selectStore: "المستودع المستقبِل",
      selectVariety: "الصنف",
      qualityScore: "نقطة الجودة /100",
      submit: "إصدار الإيصال",
      issued: "تم إصدار الإيصال بنجاح",
      scanHint: "امسح الرمز للتحقق وتتبع مسار الدفعة",
      financingRate: "نسبة التمويل",
      bankable: "قابل للتمويل البنكي",
      onlyWarehouse: "إصدار الإيصالات خاص بأعوان المستودعات المعتمدة",
      sell: "بيع الإيصال",
      sellPrice: "سعر البيع (دج/كغ)",
    },
    stores: {
      title: "شبكة المخازن الباردة المعتمدة",
      subtitle: "طاقة تخزين مرتبطة رقمياً بالمنصة في ولايات الإنتاج الرئيسية",
      capacity: "الطاقة الإجمالية",
      used: "المستخدم",
      available: "المتاح",
      utilization: "نسبة الامتلاء",
      temperature: "درجة الحرارة",
      storesCount: "عدد المخازن",
      public: "عمومي",
      private: "خاص",
      networkStatus: "حالة الربط",
      online: "متصل",
      certified: "معتمد",
      region: "المنطقة",
      desert: "جنوب صحراوي",
      coastal: "ساحلي",
      highlands: "هضاب عليا",
      producerWilayas: "ولايات الإنتاج الرئيسية",
    },
    intervention: {
      title: "غرفة تدخل الدولة — صانع السوق",
      subtitle: "ONILEV / SARPA: شراء عند الأرضية لحماية الفلاح، وبيع من المخزون عند السقف لحماية المستهلك",
      bandTitle: "نطاق التدخل",
      floorLabel: "أرضية السعر — شراء الدولة",
      ceilingLabel: "سقف السعر — بيع الدولة",
      saveBand: "تحديث النطاق",
      mmOn: "صانع السوق مفعّل",
      mmOff: "صانع السوق معطّل",
      toggleMm: "تفعيل/تعطيل",
      strategicStock: "المخزون الاستراتيجي",
      buyAction: "شراء من السوق",
      sellAction: "بيع من المخزون",
      buyHint: "ضخ سيولة شرائية لدعم الأسعار",
      sellHint: "طرح كميات لتهدئة الأسعار",
      reason: "سبب التدخل",
      execute: "تنفيذ التدخل",
      history: "سجل التدخلات",
      type: "النوع",
      beforeAfter: "السعر قبل / بعد",
      stockImpact: "أثر المخزون",
      bandUpdated: "تم تحديث نطاق التدخل",
      executed: "تم تنفيذ التدخل",
      accessDenied: "هذه الصفحة مخصصة لممثلي ONILEV / SARPA — الوضع قراءة فقط",
      volatility: "التقلب المكبوت",
      protected: "أسعار محمية ضمن النطاق",
      bandReason: "تعديل نطاق التدخل",
      selectGrade: "الدرجة",
      treasury: "خزينة التدخل",
    },
    trace: {
      title: "تتبع مسار البطاطا",
      subtitle: "نظام التتبع برمز QR — من الحقل إلى المستهلك",
      placeholder: "أدخل رمز الدفعة (LOT-…) أو رقم الإيصال (EWR-…)",
      search: "تتبع",
      journey: "مسار الدفعة",
      harvest: "الحصاد",
      inspection: "معاينة الجودة",
      intake: "استلام في المستودع",
      storage: "تخزين مبرد",
      receiptIssued: "إصدار الإيصال",
      pledged: "رهن بنكي",
      traded: "تداول في البورصة",
      delivery: "تسليم",
      notFound: "لم يُعثر على الدفعة — تحقق من الرمز",
      lotInfo: "بطاقة الدفعة",
      farmer: "الفلاح",
      events: "محطات المسار",
      tryCode: "جرّب مثالاً:",
    },
    dashboard: {
      title: "فضاء المستخدم",
      subtitle: "لوحة خاصة حسب صفتك في المنصة",
      welcome: "مرحباً",
      myWallet: "رصيد المحفظة",
      myReceipts: "إيصالاتي",
      myOrders: "أوامري",
      myTrades: "صفقاتي",
      myStore: "مخزني",
      pledgesToReview: "طلبات الرهن",
      farmerHint: "أودع إنتاجك في مخزن معتمد واحصل على إيصال قابل للتداول والرهن.",
      traderHint: "تابع أووامرك وصفقاتك وأصدر أوامر جديدة.",
      stateHint: "راقب السوق وأدر نطاق التدخل والمخزون الاستراتيجي.",
      warehouseHint: "استقبل الكميات وأصدر الإيصالات الإلكترونية.",
      bankHint: "عاين الإيصالات المرهونة ومبالغ التمويل الممنوحة.",
      processorHint: "اشترِ درجات التحويل الصناعي عبر المنصة.",
      openOrder: "أمر مفتوح",
      stockValue: "قيمة المخزون",
      financingGranted: "تمويل ممنوح",
      quickActions: "إجراءات سريعة",
      noReceipts: "لا توجد إيصالات بعد",
      noOrders: "لا توجد أوامر بعد",
      noTrades: "لا توجد صفقات بعد",
    },
    login: {
      title: "الدخول إلى المنصة",
      subtitle: "منصة عمومية تحت إشراف وزارة الفلاحة والمحافظة السامية للرقمنة",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      submit: "دخول",
      personaTitle: "دخول تجريبي سريع بالحسابات النموذجية",
      personaHint: "كل الحسابات التجريبية بكلمة مرور موحدة موضّحة على البطاقة",
      failed: "بيانات الدخول غير صحيحة",
      loggedIn: "تم الدخول بنجاح",
      demoPassword: "كلمة المرور لكافة الحسابات",
      nationalId: "هوية وطنية موحدة",
    },
    footer: {
      line1: "منصة مقترحة قابلة للتنفيذ — شراكة بين وزارة الفلاحة ووزارة التجارة الداخلية والمحافظة السامية للرقمنة.",
      line2: "استضافة وطنية سيادية — تكامل مع ONILEV، SARPA، BaridiMob والبنوك.",
      rights: "سبتمبر 2026 — الجمهورية الجزائرية الديمقراطية الشعبية",
    },
  },
  en: {
    app: {
      name: "National Potato Exchange",
      nameEn: "البورصة الوطنية للبطاطا",
      tagline: "Electronic Potato Trading Platform for the Algerian Market",
      authority: "High Commission for Digitization — State-supervised platform",
    },
    nav: {
      market: "Market",
      trading: "Trading",
      auctions: "Auctions",
      receipts: "Warehouse Receipts",
      stores: "Cold Stores",
      intervention: "State Intervention",
      trace: "Traceability",
      dashboard: "My Space",
      login: "Sign in",
      logout: "Sign out",
      language: "العربية",
      proposal: "About",
    },
    common: {
      loading: "Loading…",
      all: "All",
      status: "Status",
      actions: "Actions",
      save: "Save",
      cancel: "Cancel",
      confirm: "Confirm",
      price: "Price",
      priceKg: "Price (DZD/kg)",
      quantity: "Quantity",
      quantityQ: "Quantity (quintals)",
      grade: "Grade",
      total: "Total",
      totalValue: "Total value",
      date: "Date",
      buy: "Buy",
      sell: "Sell",
      today: "Today",
      yesterday: "Yesterday",
      perKg: "DZD/kg",
      quintal: "quintal",
      quintals: "quintals",
      ton: "ton",
      dzd: "DZD",
      live: "LIVE",
      refresh: "Refresh",
      noData: "No data",
      search: "Search by receipt or lot code…",
      volume: "Volume",
      bid: "Bid",
      ask: "Ask",
      spread: "Spread",
      depth: "Market depth",
      recentTrades: "Recent trades",
      orderBook: "Order book",
      placeOrder: "Place order",
      orderType: "Order type",
      limit: "Limit",
      auction: "Auction",
      open: "Open",
      partial: "Partial",
      filled: "Filled",
      cancelled: "Cancelled",
      active: "Active",
      pledged: "Pledged",
      transferred: "Transferred",
      delivered: "Delivered",
      settled: "Settled",
      inspected: "Inspected",
      pending: "Pending",
      buyer: "Buyer",
      seller: "Seller",
      holder: "Holder",
      view: "View",
      details: "Details",
      back: "Back",
      official: "Official",
      certified: "Certified",
      connected: "Digitally connected",
      demo: "Demo data",
      wallet: "Wallet",
      gradeA: "Grade A — Export / Premium",
      gradeB: "Grade B — Standard consumption",
      gradeC: "Grade C — Industrial processing",
      variety: "Variety",
      wilaya: "Wilaya",
      code: "Code",
      role: "Role",
      loginAs: "Sign in as",
      minutes: "min",
      hours: "h",
      days: "d",
      closed: "Closed",
      winner: "Winner",
      settlePrice: "Settlement price",
      quantityAvailable: "Available qty",
    },
    roles: {
      farmer: "Farmer",
      trader: "Trader",
      state: "Public body (ONILEV)",
      warehouse: "Cold warehouse",
      bank: "Bank",
      processor: "Processor",
      admin: "Regulator",
    },
    landing: {
      heroBadge: "State-supervised executable project",
      heroTitle: "A national spot exchange for potatoes",
      heroSubtitle:
        "Transparent trading, bankable electronic warehouse receipts, and a state market maker protecting farmers and consumers",
      ctaTrade: "Start trading",
      ctaProposal: "Platform components",
      statProduction: "Annual production",
      statConsumption: "National consumption",
      statStock: "Strategic stock",
      statVolatility: "Historical price range",
      marketTitle: "Today's market index",
      marketSubtitle: "Reference price and registered volume on the platform",
      refPrice: "Reference price",
      floor: "Buy-back intervention floor",
      ceiling: "Sell-from-stock ceiling",
      todayVolume: "Today's volume",
      stateStock: "State strategic stock",
      chartTitle: "Price evolution — last 120 days",
      chartSubtitle: "With the state intervention band suppressing volatility",
      componentsTitle: "Platform components",
      componentsSubtitle: "Five interconnected components operated under ministerial supervision",
      cSpotTitle: "Spot trading",
      cSpotText: "Daily auctions and continuous order matching for fair, transparent price discovery.",
      cReceiptTitle: "Warehouse receipts",
      cReceiptText: "Certified electronic receipts, tradable and pledgeable to banks for financing.",
      cMmTitle: "State as market maker",
      cMmText: "Buys when prices fall and releases strategic stock when prices rise.",
      cQualityTitle: "Quality & standards",
      cQualityText: "Certified grading (class, size, moisture) linked to cold stores and labs.",
      cIntegrationTitle: "Digital integration",
      cIntegrationText: "Connected to BaridiMob, banks, the CNRC trade register and local payment rails.",
      roadmapTitle: "Implementation roadmap (18–24 months)",
      phases: "Four phases",
      phase1Title: "Preparation — 3 to 4 months",
      phase1Text: "Steering committee, feasibility study, legal drafting, system design.",
      phase2Title: "Build — 6 to 8 months",
      phase2Text: "Platform development, warehouse connectivity, training, MVP release.",
      phase3Title: "Pilot — 4 to 6 months",
      phase3Text: "Trial launch in 2–3 producing wilayas, evaluation and improvements.",
      phase4Title: "Rollout — 5 to 6 months",
      phase4Text: "Nationwide expansion, full integration, official launch, monitoring.",
      legalTitle: "Legal framework",
      legalText:
        "E-commerce law 18-05, ONILEV & SARPA mandates, Syrpalac mechanism, and founding texts for warehouse receipts and market making.",
      offlineTitle: "Works everywhere",
      offlineText: "Offline-first app, simple Arabic UX, SMS/USSD support, local agents and sovereign national hosting.",
    },
    trading: {
      title: "Trading floor",
      subtitle: "Continuous order matching — price discovery between supply and demand within the state band",
      buy: "Buy order",
      sell: "Sell order",
      buyDesc: "Register a bid at your chosen price",
      sellDesc: "Sell your produce or receipt directly on the market",
      pricePlaceholder: "Max buy price (DZD/kg)",
      pricePlaceholderSell: "Min sell price (DZD/kg)",
      qtyPlaceholder: "Quantity in quintals",
      submitBuy: "Submit buy order",
      submitSell: "Submit sell order",
      myOrders: "My orders",
      bestBid: "Best bid",
      bestAsk: "Best ask",
      marketTick: "Market tick",
      tickHint: "Simulate new incoming orders and matching",
      orderPlaced: "Order registered and matched",
      orderFailed: "Could not place the order",
      orderCancelled: "Order cancelled",
      cancel: "Cancel",
      stateLiquidity: "State liquidity at the band edges",
      bidQty: "Bid qty",
      askQty: "Ask qty",
      priceLevel: "Price",
      matched: "Matched",
      noReceipt: "Free sale (forward delivery)",
      againstReceipt: "Against warehouse receipt",
      selectReceipt: "Select a receipt to sell…",
      connectToTrade: "Sign in to place orders",
      selectGrade: "Select grade",
      fundHint: "Amount is settled against the wallet on matching",
      sellReceiptHint: "A receipt-backed sale transfers ownership of stored goods",
      depthTitle: "Market depth (cumulative)",
      stateOrder: "State order",
    },
    auctions: {
      title: "Daily auctions",
      subtitle: "Uniform-price auction closing daily at 11:00 — produce clears at the highest closing price",
      liveAuction: "Live auction",
      scheduledAt: "Closing time",
      quantityOffered: "Quantity offered",
      leadingBid: "Leading bid",
      bidCount: "Bids",
      placeBid: "Place a bid",
      yourBid: "Your bid (DZD/kg)",
      settled: "Settled auctions",
      settle: "Settle auction now",
      settledAt: "Settlement price",
      seller: "Seller",
      noLive: "No live auction at the moment",
      pastResults: "Previous auction results",
      bidPlaced: "Your bid was registered",
      settledOk: "Auction settled",
      loginToBid: "Sign in to place a bid",
      qtyBid: "Wanted quantity (quintals)",
      remaining: "Until closing",
    },
    receipts: {
      title: "Electronic warehouse receipts",
      subtitle: "A title of ownership, tradable and bankable, issued by a certified cold warehouse",
      issue: "Issue new receipt",
      myReceipts: "My receipts",
      allReceipts: "All receipts",
      code: "Receipt N°",
      lot: "Lot",
      store: "Warehouse",
      issueDate: "Issue date",
      available: "Available qty",
      pledge: "Pledge to bank",
      pledgeHint: "Financing up to 70% of the receipt value",
      pledged: "Pledged",
      pledgeAmount: "Financing amount",
      release: "Release pledge",
      sellOnExchange: "Sell on exchange",
      transfer: "Transfer ownership",
      trace: "Track lot",
      farmer: "Farmer",
      newReceiptTitle: "Deposit produce & issue receipt",
      selectFarmer: "Depositing farmer",
      selectStore: "Receiving warehouse",
      selectVariety: "Variety",
      qualityScore: "Quality score /100",
      submit: "Issue receipt",
      issued: "Receipt issued successfully",
      scanHint: "Scan to verify and trace the lot's journey",
      financingRate: "Financing rate",
      bankable: "Bankable",
      onlyWarehouse: "Receipt issuance is restricted to certified warehouse operators",
      sell: "Sell receipt",
      sellPrice: "Sell price (DZD/kg)",
    },
    stores: {
      title: "Certified cold store network",
      subtitle: "Storage capacity digitally connected across the main producing wilayas",
      capacity: "Total capacity",
      used: "Used",
      available: "Available",
      utilization: "Utilization",
      temperature: "Temperature",
      storesCount: "Stores",
      public: "Public",
      private: "Private",
      networkStatus: "Connectivity",
      online: "Online",
      certified: "Certified",
      region: "Region",
      desert: "Saharan South",
      coastal: "Coastal",
      highlands: "High plateaus",
      producerWilayas: "Major producing wilayas",
    },
    intervention: {
      title: "State intervention room — Market maker",
      subtitle: "ONILEV / SARPA: buying at the floor to protect farmers, selling from stock at the ceiling to protect consumers",
      bandTitle: "Intervention band",
      floorLabel: "Price floor — state buys",
      ceilingLabel: "Price ceiling — state sells",
      saveBand: "Update band",
      mmOn: "Market maker enabled",
      mmOff: "Market maker disabled",
      toggleMm: "Enable / disable",
      strategicStock: "Strategic stock",
      buyAction: "Buy from market",
      sellAction: "Sell from stock",
      buyHint: "Inject buying liquidity to support prices",
      sellHint: "Release quantities to cool prices",
      reason: "Reason",
      execute: "Execute intervention",
      history: "Intervention log",
      type: "Type",
      beforeAfter: "Price before / after",
      stockImpact: "Stock impact",
      bandUpdated: "Intervention band updated",
      executed: "Intervention executed",
      accessDenied: "Restricted to ONILEV / SARPA operators — read-only view",
      volatility: "Capped volatility",
      protected: "Prices protected within the band",
      bandReason: "Band adjustment",
      selectGrade: "Grade",
      treasury: "Intervention treasury",
    },
    trace: {
      title: "Potato journey traceability",
      subtitle: "QR-based traceability — from field to consumer",
      placeholder: "Enter a lot code (LOT-…) or receipt number (EWR-…)",
      search: "Trace",
      journey: "Lot journey",
      harvest: "Harvest",
      inspection: "Quality inspection",
      intake: "Warehouse intake",
      storage: "Cold storage",
      receiptIssued: "Receipt issued",
      pledged: "Bank pledge",
      traded: "Exchange trade",
      delivery: "Delivery",
      notFound: "Lot not found — check the code",
      lotInfo: "Lot card",
      farmer: "Farmer",
      events: "Journey stages",
      tryCode: "Try an example:",
    },
    dashboard: {
      title: "My space",
      subtitle: "A role-based dashboard on the platform",
      welcome: "Welcome",
      myWallet: "Wallet balance",
      myReceipts: "My receipts",
      myOrders: "My orders",
      myTrades: "My trades",
      myStore: "My warehouse",
      pledgesToReview: "Pledge requests",
      farmerHint: "Deposit your produce in a certified warehouse and obtain a tradable, bankable receipt.",
      traderHint: "Track your orders and trades and place new ones.",
      stateHint: "Monitor the market and manage the intervention band and strategic stock.",
      warehouseHint: "Receive quantities and issue electronic receipts.",
      bankHint: "Review pledged receipts and granted financing.",
      processorHint: "Buy industrial-processing grades on the platform.",
      openOrder: "Open order",
      stockValue: "Stock value",
      financingGranted: "Financing granted",
      quickActions: "Quick actions",
      noReceipts: "No receipts yet",
      noOrders: "No orders yet",
      noTrades: "No trades yet",
    },
    login: {
      title: "Sign in to the platform",
      subtitle: "A public platform under the Ministry of Agriculture and the High Commission for Digitization",
      email: "Email",
      password: "Password",
      submit: "Sign in",
      personaTitle: "Quick demo sign-in with model accounts",
      personaHint: "All demo accounts share the password shown on the card",
      failed: "Invalid credentials",
      loggedIn: "Signed in successfully",
      demoPassword: "Shared password for all accounts",
      nationalId: "Unified national identity",
    },
    footer: {
      line1: "Executable proposed platform — partnership of the Ministries of Agriculture, Internal Trade and the High Commission for Digitization.",
      line2: "Sovereign national hosting — integrated with ONILEV, SARPA, BaridiMob and banks.",
      rights: "September 2026 — People's Democratic Republic of Algeria",
    },
  },
} as const;

export type Lang = "ar" | "en";
type Dict = (typeof dict)["ar"];

function resolve(obj: unknown, path: string): string | undefined {
  let cur: unknown = obj;
  for (const part of path.split(".")) {
    if (cur && typeof cur === "object" && part in (cur as Record<string, unknown>)) {
      cur = (cur as Record<string, unknown>)[part];
    } else return undefined;
  }
  return typeof cur === "string" ? cur : undefined;
}

export type TFunc = (key: string) => string;

export function makeT(lang: Lang): TFunc {
  return (key: string) =>
    resolve(dict[lang], key) ?? resolve(dict.en, key) ?? key;
}

export type { Dict };
